// This file is auto-generated by generate_file_list.bat. DO NOT EDIT.

const memoryHazeImages = [
   "Screenshot 2026-02-08 205852.png",
   "Screenshot 2026-02-08 205954.png",
   "Screenshot 2026-02-08 210035.png",
   "Screenshot 2026-02-08 210142.png",
   "Screenshot 2026-02-08 210249.png",
   "Screenshot 2026-02-08 210352.png",
   "Screenshot 2026-02-09 100712.png",
   "Screenshot 2026-02-09 140240.png",
];

const galleryImages = [
   "Screenshot 2026-02-08 205852.png",
   "Screenshot 2026-02-08 205954.png",
   "Screenshot 2026-02-08 210035.png",
   "Screenshot 2026-02-08 210142.png",
   "Screenshot 2026-02-08 210249.png",
   "Screenshot 2026-02-08 210352.png",
   "Screenshot 2026-02-09 100712.png",
   "Screenshot 2026-02-09 140240.png",
];

const polaroidImages = [
   "Screenshot 2026-02-08 205852.png",
   "Screenshot 2026-02-08 205954.png",
   "Screenshot 2026-02-08 210035.png",
   "Screenshot 2026-02-08 210142.png",
   "Screenshot 2026-02-08 210249.png",
   "Screenshot 2026-02-08 210352.png",
   "Screenshot 2026-02-09 100712.png",
   "Screenshot 2026-02-09 140240.png",
];
