@echo off
SETLOCAL ENABLEDELAYEDEXPANSION

REM This script automatically finds all the images in your assets folders
REM and creates a 'file_list.js' file for the webpage to use.

ECHO Generating file list...

(
    echo // This file is auto-generated by generate_file_list.bat. DO NOT EDIT.
    echo.
    
    echo const memoryHazeImages = [
    for %%f in ("assets\memory_haze\*.*") do (
        echo    "%%~nxf",
    )
    echo ];
    echo.

    echo const galleryImages = [
    for %%f in ("assets\gallery\*.*") do (
        echo    "%%~nxf",
    )
    echo ];
    echo.

    echo const polaroidImages = [
    for %%f in ("assets\polaroids\*.*") do (
        echo    "%%~nxf",
    )
    echo ];
) > file_list.js

ECHO Done. The file_list.js has been updated.
ENDLOCAL
